package OBSOLETE_jdbc;


public enum CrudStateEnum
{
	NONE,
	CREATED,
		CREATE_BEFORE,
		CREATE_MERGE_INITIAL_DATA,
		CREATE_PROCESS,
		CREATE_SET_PRIMARY_KEY,
		CREATE_AFTER,
	READ,
		READ_BEFORE,
		READ_PROCESS,
		READ_CHECK_PRIMARY_KEY,
		READ_AFTER,
	UPDATED,
		UPDATE_BEFORE,
		UPDATE_PROCESS,
		UPDATE_CHECK_PRIMARY_KEY,
		UPDATE_AFTER,
	DELETED,
		DELETE_BEFORE,
		DELETE_PROCESS,
		DELETE_CHECK_PRIMARY_KEY,
		DELETE_AFTER,
	;
}
